# Generated by Django 3.1.4 on 2020-12-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201208_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
