# Generated by Django 3.1.4 on 2020-12-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201208_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvresume',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='cvresume',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/'),
        ),
    ]
